# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ml_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'ml_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10ml_service.proto\x12\nml_service\"\xab\x01\n\x0bTransaction\x12\x0b\n\x03\x61mt\x18\x01 \x01(\x01\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x0e\n\x06gender\x18\x03 \x01(\t\x12\x10\n\x08\x63ity_pop\x18\x04 \x01(\x05\x12\x0b\n\x03lat\x18\x05 \x01(\x01\x12\x0c\n\x04long\x18\x06 \x01(\x01\x12\x11\n\tmerch_lat\x18\x07 \x01(\x01\x12\x12\n\nmerch_long\x18\x08 \x01(\x01\x12\x0c\n\x04hour\x18\t \x01(\x05\x12\x0b\n\x03\x61ge\x18\n \x01(\x05\":\n\x10TransactionBatch\x12&\n\x05items\x18\x01 \x03(\x0b\x32\x17.ml_service.Transaction\"J\n\nPrediction\x12\x10\n\x08is_fraud\x18\x01 \x01(\x08\x12\x13\n\x0bprobability\x18\x02 \x01(\x01\x12\x15\n\rmodel_version\x18\x03 \x01(\t2\x90\x01\n\tMLService\x12:\n\x07Predict\x12\x17.ml_service.Transaction\x1a\x16.ml_service.Prediction\x12G\n\rPredictStream\x12\x1c.ml_service.TransactionBatch\x1a\x16.ml_service.Prediction0\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ml_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTION']._serialized_start=33
  _globals['_TRANSACTION']._serialized_end=204
  _globals['_TRANSACTIONBATCH']._serialized_start=206
  _globals['_TRANSACTIONBATCH']._serialized_end=264
  _globals['_PREDICTION']._serialized_start=266
  _globals['_PREDICTION']._serialized_end=340
  _globals['_MLSERVICE']._serialized_start=343
  _globals['_MLSERVICE']._serialized_end=487
# @@protoc_insertion_point(module_scope)
