# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fraud/api/proto/fraud.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'fraud/api/proto/fraud.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x66raud/api/proto/fraud.proto\x12\x05\x66raud\"\xab\x01\n\x0bTransaction\x12\x0b\n\x03\x61mt\x18\x01 \x01(\x01\x12\x10\n\x08\x63\x61tegory\x18\x02 \x01(\t\x12\x0e\n\x06gender\x18\x03 \x01(\t\x12\x10\n\x08\x63ity_pop\x18\x04 \x01(\x05\x12\x0b\n\x03lat\x18\x05 \x01(\x01\x12\x0c\n\x04long\x18\x06 \x01(\x01\x12\x11\n\tmerch_lat\x18\x07 \x01(\x01\x12\x12\n\nmerch_long\x18\x08 \x01(\x01\x12\x0c\n\x04hour\x18\t \x01(\x05\x12\x0b\n\x03\x61ge\x18\n \x01(\x05\"5\n\x10TransactionBatch\x12!\n\x05items\x18\x01 \x03(\x0b\x32\x12.fraud.Transaction\"J\n\nPrediction\x12\x10\n\x08is_fraud\x18\x01 \x01(\x08\x12\x13\n\x0bprobability\x18\x02 \x01(\x01\x12\x15\n\rmodel_version\x18\x03 \x01(\t\"\x07\n\x05\x45mpty\"*\n\tModelInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t2\xaf\x01\n\x0c\x46raudScoring\x12\x30\n\x07Predict\x12\x12.fraud.Transaction\x1a\x11.fraud.Prediction\x12=\n\rPredictStream\x12\x17.fraud.TransactionBatch\x1a\x11.fraud.Prediction0\x01\x12.\n\x0cGetModelInfo\x12\x0c.fraud.Empty\x1a\x10.fraud.ModelInfob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud.api.proto.fraud_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRANSACTION']._serialized_start=39
  _globals['_TRANSACTION']._serialized_end=210
  _globals['_TRANSACTIONBATCH']._serialized_start=212
  _globals['_TRANSACTIONBATCH']._serialized_end=265
  _globals['_PREDICTION']._serialized_start=267
  _globals['_PREDICTION']._serialized_end=341
  _globals['_EMPTY']._serialized_start=343
  _globals['_EMPTY']._serialized_end=350
  _globals['_MODELINFO']._serialized_start=352
  _globals['_MODELINFO']._serialized_end=394
  _globals['_FRAUDSCORING']._serialized_start=397
  _globals['_FRAUDSCORING']._serialized_end=572
# @@protoc_insertion_point(module_scope)
