# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from fraud.api.proto import fraud_pb2 as fraud_dot_api_dot_proto_dot_fraud__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in fraud/api/proto/fraud_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FraudScoringStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Predict = channel.unary_unary(
                '/fraud.FraudScoring/Predict',
                request_serializer=fraud_dot_api_dot_proto_dot_fraud__pb2.Transaction.SerializeToString,
                response_deserializer=fraud_dot_api_dot_proto_dot_fraud__pb2.Prediction.FromString,
                _registered_method=True)
        self.PredictStream = channel.unary_stream(
                '/fraud.FraudScoring/PredictStream',
                request_serializer=fraud_dot_api_dot_proto_dot_fraud__pb2.TransactionBatch.SerializeToString,
                response_deserializer=fraud_dot_api_dot_proto_dot_fraud__pb2.Prediction.FromString,
                _registered_method=True)
        self.GetModelInfo = channel.unary_unary(
                '/fraud.FraudScoring/GetModelInfo',
                request_serializer=fraud_dot_api_dot_proto_dot_fraud__pb2.Empty.SerializeToString,
                response_deserializer=fraud_dot_api_dot_proto_dot_fraud__pb2.ModelInfo.FromString,
                _registered_method=True)


class FraudScoringServicer:
    """Missing associated documentation comment in .proto file."""

    def Predict(self, request, context):
        """unary: 1 transacción -> 1 predicción
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PredictStream(self, request, context):
        """server streaming: 1 lote -> N predicciones (una por transacción del lote)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelInfo(self, request, context):
        """unary: pedir sólo name + version (para comparar con REST y GraphQL)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FraudScoringServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Predict': grpc.unary_unary_rpc_method_handler(
                    servicer.Predict,
                    request_deserializer=fraud_dot_api_dot_proto_dot_fraud__pb2.Transaction.FromString,
                    response_serializer=fraud_dot_api_dot_proto_dot_fraud__pb2.Prediction.SerializeToString,
            ),
            'PredictStream': grpc.unary_stream_rpc_method_handler(
                    servicer.PredictStream,
                    request_deserializer=fraud_dot_api_dot_proto_dot_fraud__pb2.TransactionBatch.FromString,
                    response_serializer=fraud_dot_api_dot_proto_dot_fraud__pb2.Prediction.SerializeToString,
            ),
            'GetModelInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelInfo,
                    request_deserializer=fraud_dot_api_dot_proto_dot_fraud__pb2.Empty.FromString,
                    response_serializer=fraud_dot_api_dot_proto_dot_fraud__pb2.ModelInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fraud.FraudScoring', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fraud.FraudScoring', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FraudScoring:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Predict(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fraud.FraudScoring/Predict',
            fraud_dot_api_dot_proto_dot_fraud__pb2.Transaction.SerializeToString,
            fraud_dot_api_dot_proto_dot_fraud__pb2.Prediction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PredictStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/fraud.FraudScoring/PredictStream',
            fraud_dot_api_dot_proto_dot_fraud__pb2.TransactionBatch.SerializeToString,
            fraud_dot_api_dot_proto_dot_fraud__pb2.Prediction.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetModelInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fraud.FraudScoring/GetModelInfo',
            fraud_dot_api_dot_proto_dot_fraud__pb2.Empty.SerializeToString,
            fraud_dot_api_dot_proto_dot_fraud__pb2.ModelInfo.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
